### PR TITLE
`Mod:getPath`: replace the path slash properly

### PR DESCRIPTION
**Pull request by Sword352**
Bro fogot `.replace` does NOT modify the string in place 😭😭😭😭🙏🙏

### CODE REVIEW

**Comment by libauror-a** [comment]
a.

**Comment by Sword352** [comment]
B c d e f g h i j k l m n o p q r s t u v w x y z

This u lil bro?
2023_02_13_oak-wood-plank-camo-21331566
Screenshot_20230727_131441_Roblox

**Comment by libauror-a** [comment]
can you shur.up man??? uuggghhh shakes butt

**Comment by Sword352** [comment]
https://cdn.discordapp.com/attachments/1126588194977218712/1134919721490337812/SPOILER_lv_0_20230729194320.mp4

**Pull request merged**
